default_hosts: &default_host
  hosts:
    - <%= Peas::CONTROLLER_DOMAIN %>:27017

production:
  sessions:
    default:
      database: peas
      <<: *default_host

development:
  sessions:
    default:
      database: peas_dev
      <<: *default_host

test:
  sessions:
    default:
      database: peas_test
      <<: *default_host
